"""add iyf

Revision ID: 10167050b272
Revises: 52af44c37c17
Create Date: 2025-11-30 21:27:41.735098

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '10167050b272'
down_revision = '52af44c37c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iyf_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iyf_id', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('title', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('cover_url', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('description', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('category', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('rating', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('crawl_date', sa.String(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iyf_video_dept_id'), 'iyf_video', ['dept_id'], unique=False)
    op.drop_index('app_code_key', table_name='app')
    op.create_unique_constraint(None, 'app', ['code'])
    op.drop_index('fsa_manage_fsa_key', table_name='fsa_manage')
    op.create_unique_constraint(None, 'fsa_manage', ['fsa'])
    op.drop_index('gas_station_station_id_key', table_name='gas_station')
    op.create_unique_constraint(None, 'gas_station', ['station_id'])
    op.drop_index('permission_code_key', table_name='permission')
    op.create_unique_constraint(None, 'permission', ['code'])
    op.drop_index('shop_code_key', table_name='shop')
    op.create_unique_constraint(None, 'shop', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='unique')
    op.create_index('shop_code_key', 'shop', ['code'], unique=True)
    op.drop_constraint(None, 'permission', type_='unique')
    op.create_index('permission_code_key', 'permission', ['code'], unique=True)
    op.drop_constraint(None, 'gas_station', type_='unique')
    op.create_index('gas_station_station_id_key', 'gas_station', ['station_id'], unique=True)
    op.drop_constraint(None, 'fsa_manage', type_='unique')
    op.create_index('fsa_manage_fsa_key', 'fsa_manage', ['fsa'], unique=True)
    op.drop_constraint(None, 'app', type_='unique')
    op.create_index('app_code_key', 'app', ['code'], unique=True)
    op.drop_index(op.f('ix_iyf_video_dept_id'), table_name='iyf_video')
    op.drop_table('iyf_video')
    # ### end Alembic commands ###
