"""modfy column 

Revision ID: 1bb54938e0db
Revises: 772fcbcdadb4
Create Date: 2025-12-26 08:33:32.805260

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '1bb54938e0db'
down_revision = '772fcbcdadb4'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """检查列是否存在"""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查并添加 study_session.question_count（如果不存在）
    if not column_exists('study_session', 'question_count'):
        op.add_column('study_session', sa.Column('question_count', sa.Integer(), server_default=sa.text('20'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_session', 'question_count')
    # ### end Alembic commands ###
