"""add study

Revision ID: 335eb6c81e91
Revises: 36186ff543fc
Create Date: 2025-12-20 11:49:32.403157

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '335eb6c81e91'
down_revision = '36186ff543fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('name', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('description', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('staus', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_exam_code'), 'study_exam', ['code'], unique=True)
    op.create_index(op.f('ix_study_exam_dept_id'), 'study_exam', ['dept_id'], unique=False)
    op.create_table('study_knowledge_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('title', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('description', sa.String(length=9999), server_default=sa.text("''"), nullable=False),
    sa.Column('importance', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_knowledge_node_code'), 'study_knowledge_node', ['code'], unique=True)
    op.create_index(op.f('ix_study_knowledge_node_dept_id'), 'study_knowledge_node', ['dept_id'], unique=False)
    op.create_table('study_knowledge_source_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_node_id', sa.Integer(), nullable=False),
    sa.Column('source_section_id', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_knowledge_source_section_dept_id'), 'study_knowledge_source_section', ['dept_id'], unique=False)
    op.create_table('study_learning_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_learning_item_dept_id'), 'study_learning_item', ['dept_id'], unique=False)
    op.create_table('study_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('stem', sa.String(length=9999), server_default=sa.text("''"), nullable=False),
    sa.Column('options', sa.String(length=9999), server_default=sa.text("''"), nullable=False),
    sa.Column('answer', sa.String(length=9999), server_default=sa.text("''"), nullable=False),
    sa.Column('explanation_raw', sa.String(length=9999), server_default=sa.text("''"), nullable=False),
    sa.Column('explanation_human', sa.String(length=9999), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_question_dept_id'), 'study_question', ['dept_id'], unique=False)
    op.create_table('study_question_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_node_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_question_knowledge_dept_id'), 'study_question_knowledge', ['dept_id'], unique=False)
    op.create_table('study_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('start_time', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('end_time', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_session_dept_id'), 'study_session', ['dept_id'], unique=False)
    op.create_table('study_session_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('learning_item_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('time_spent_second', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_session_item_dept_id'), 'study_session_item', ['dept_id'], unique=False)
    op.create_table('study_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('title', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('version', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_source_dept_id'), 'study_source', ['dept_id'], unique=False)
    op.create_table('study_source_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('section', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('anchor_text', sa.String(length=1024), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_source_section_dept_id'), 'study_source_section', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_source_section_dept_id'), table_name='study_source_section')
    op.drop_table('study_source_section')
    op.drop_index(op.f('ix_study_source_dept_id'), table_name='study_source')
    op.drop_table('study_source')
    op.drop_index(op.f('ix_study_session_item_dept_id'), table_name='study_session_item')
    op.drop_table('study_session_item')
    op.drop_index(op.f('ix_study_session_dept_id'), table_name='study_session')
    op.drop_table('study_session')
    op.drop_index(op.f('ix_study_question_knowledge_dept_id'), table_name='study_question_knowledge')
    op.drop_table('study_question_knowledge')
    op.drop_index(op.f('ix_study_question_dept_id'), table_name='study_question')
    op.drop_table('study_question')
    op.drop_index(op.f('ix_study_learning_item_dept_id'), table_name='study_learning_item')
    op.drop_table('study_learning_item')
    op.drop_index(op.f('ix_study_knowledge_source_section_dept_id'), table_name='study_knowledge_source_section')
    op.drop_table('study_knowledge_source_section')
    op.drop_index(op.f('ix_study_knowledge_node_dept_id'), table_name='study_knowledge_node')
    op.drop_index(op.f('ix_study_knowledge_node_code'), table_name='study_knowledge_node')
    op.drop_table('study_knowledge_node')
    op.drop_index(op.f('ix_study_exam_dept_id'), table_name='study_exam')
    op.drop_index(op.f('ix_study_exam_code'), table_name='study_exam')
    op.drop_table('study_exam')
    # ### end Alembic commands ###
