"""Add column play_url in iyfVideo

Revision ID: 36186ff543fc
Revises: 9b4ebaefc415
Create Date: 2025-12-16 17:17:36.893656

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36186ff543fc'
down_revision = '9b4ebaefc415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iyf_video', sa.Column('play_url', sa.String(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iyf_video', 'play_url')
    # ### end Alembic commands ###
