"""Add posted_time to gas_price

Revision ID: 52af44c37c17
Revises: a212b58a99e1
Create Date: 2025-11-21 15:00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52af44c37c17'
down_revision = 'a212b58a99e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gas_price', sa.Column('posted_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gas_price', 'posted_time')
    # ### end Alembic commands ###


