"""Add gasbuddy models

Revision ID: 670df2eed99a
Revises: 67fb75e7c316
Create Date: 2025-11-20 12:17:43.021589

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '670df2eed99a'
down_revision = '67fb75e7c316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('postcode', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('fuel_product', sa.Integer(), nullable=False),
    sa.Column('cash_price', sa.String(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('cash_formatted_price', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('crawl_time', sa.String(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_price_dept_id'), 'gas_price', ['dept_id'], unique=False)
    op.create_table('gas_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('name', sa.String(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('distance', sa.String(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('postcode', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('address', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id')
    )
    op.create_index(op.f('ix_gas_station_dept_id'), 'gas_station', ['dept_id'], unique=False)
    op.create_table('gas_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('today_avg', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('today_low', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('trend', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('crawl_time', sa.String(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_trends_dept_id'), 'gas_trends', ['dept_id'], unique=False)
    op.create_table('user_postcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('label', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_postcode_dept_id'), 'user_postcode', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_postcode_dept_id'), table_name='user_postcode')
    op.drop_table('user_postcode')
    op.drop_index(op.f('ix_gas_trends_dept_id'), table_name='gas_trends')
    op.drop_table('gas_trends')
    op.drop_index(op.f('ix_gas_station_dept_id'), table_name='gas_station')
    op.drop_table('gas_station')
    op.drop_index(op.f('ix_gas_price_dept_id'), table_name='gas_price')
    op.drop_table('gas_price')
    # ### end Alembic commands ###
