"""Add gas_postcode

Revision ID: 67fb75e7c316
Revises: badca344f590
Create Date: 2025-11-19 21:08:23.323923

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67fb75e7c316'
down_revision = 'badca344f590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_postcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.String(length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('display_name', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('latitude', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('longitude', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('region_code', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_postcode_dept_id'), 'gas_postcode', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gas_postcode_postcode'), 'gas_postcode', ['postcode'], unique=True)
    op.drop_table('seq_report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seq_report',
    sa.Column('schema_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seq_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_value', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_called', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('next_value', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('table_max', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('in_sync', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('report_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_gas_postcode_postcode'), table_name='gas_postcode')
    op.drop_index(op.f('ix_gas_postcode_dept_id'), table_name='gas_postcode')
    op.drop_table('gas_postcode')
    # ### end Alembic commands ###
