"""modfy column 

Revision ID: 772fcbcdadb4
Revises: add_progress_to_session
Create Date: 2025-12-26 08:04:45.799960

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '772fcbcdadb4'
down_revision = 'add_progress_to_session'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """检查列是否存在"""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查并添加 study_exam.exam_duration
    if not column_exists('study_exam', 'exam_duration'):
        op.add_column('study_exam', sa.Column('exam_duration', sa.Integer(), server_default=sa.text('60'), nullable=False))
    
    # 检查并添加 study_session.exam_duration
    if not column_exists('study_session', 'exam_duration'):
        op.add_column('study_session', sa.Column('exam_duration', sa.Integer(), nullable=True))
    
    # 检查并添加 study_session.question_count
    if not column_exists('study_session', 'question_count'):
        op.add_column('study_session', sa.Column('question_count', sa.Integer(), server_default=sa.text('20'), nullable=True))
    
    # 检查并删除列
    if column_exists('study_session', 'end_time'):
        op.drop_column('study_session', 'end_time')
    if column_exists('study_session', 'start_time'):
        op.drop_column('study_session', 'start_time')
    # 注意：note 字段保留，不要删除
    # op.drop_column('study_session_item', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：note 字段保留，不需要重新添加
    # op.add_column('study_session_item', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('study_session', sa.Column('start_time', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('study_session', sa.Column('end_time', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('study_session', 'question_count')
    op.drop_column('study_session', 'exam_duration')
    op.drop_column('study_exam', 'exam_duration')
    # ### end Alembic commands ###
