"""add_latest_iyf_id_to_email_history

Revision ID: 9b4ebaefc415
Revises: a0d5f0194f70
Create Date: 2025-11-30 22:46:00.611896

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9b4ebaefc415'
down_revision = 'a0d5f0194f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iyf_email_history', sa.Column('latest_iyf_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_iyf_email_history_latest_iyf_id'), 'iyf_email_history', ['latest_iyf_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iyf_email_history_latest_iyf_id'), table_name='iyf_email_history')
    op.drop_column('iyf_email_history', 'latest_iyf_id')
    # ### end Alembic commands ###
