"""add_iyf_email_history

Revision ID: a0d5f0194f70
Revises: 10167050b272
Create Date: 2025-11-30 22:35:53.837774

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a0d5f0194f70'
down_revision = '10167050b272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iyf_email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('video_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('video_ids', sa.Text(), nullable=True),
    sa.Column('video_titles', sa.Text(), nullable=True),
    sa.Column('sent_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'success'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iyf_email_history_dept_id'), 'iyf_email_history', ['dept_id'], unique=False)
    op.create_index(op.f('ix_iyf_email_history_email'), 'iyf_email_history', ['email'], unique=False)
    op.create_index(op.f('ix_iyf_email_history_id'), 'iyf_email_history', ['id'], unique=False)
    op.create_index(op.f('ix_iyf_email_history_sent_time'), 'iyf_email_history', ['sent_time'], unique=False)
    op.create_index(op.f('ix_iyf_email_history_user_id'), 'iyf_email_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iyf_email_history_user_id'), table_name='iyf_email_history')
    op.drop_index(op.f('ix_iyf_email_history_sent_time'), table_name='iyf_email_history')
    op.drop_index(op.f('ix_iyf_email_history_id'), table_name='iyf_email_history')
    op.drop_index(op.f('ix_iyf_email_history_email'), table_name='iyf_email_history')
    op.drop_index(op.f('ix_iyf_email_history_dept_id'), table_name='iyf_email_history')
    op.drop_table('iyf_email_history')
    # ### end Alembic commands ###
