"""Add gas_email_history

Revision ID: a212b58a99e1
Revises: 670df2eed99a
Create Date: 2025-11-21 12:35:04

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a212b58a99e1'
down_revision = '670df2eed99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_type', sa.String(length=32), server_default=sa.text("'alert'"), nullable=False),
    sa.Column('sent_time', sa.DateTime(), nullable=False),
    sa.Column('postcode', sa.String(length=32), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_email_history_dept_id'), 'gas_email_history', ['dept_id'], unique=False)
    op.create_index(op.f('ix_gas_email_history_email_type'), 'gas_email_history', ['email_type'], unique=False)
    op.create_index(op.f('ix_gas_email_history_id'), 'gas_email_history', ['id'], unique=False)
    op.create_index(op.f('ix_gas_email_history_sent_time'), 'gas_email_history', ['sent_time'], unique=False)
    op.create_index(op.f('ix_gas_email_history_user_id'), 'gas_email_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gas_email_history_user_id'), table_name='gas_email_history')
    op.drop_index(op.f('ix_gas_email_history_sent_time'), table_name='gas_email_history')
    op.drop_index(op.f('ix_gas_email_history_id'), table_name='gas_email_history')
    op.drop_index(op.f('ix_gas_email_history_email_type'), table_name='gas_email_history')
    op.drop_index(op.f('ix_gas_email_history_dept_id'), table_name='gas_email_history')
    op.drop_table('gas_email_history')
    # ### end Alembic commands ###

