"""add image_url

Revision ID: a6384ed4df09
Revises: 7bff4491b4a2
Create Date: 2025-12-22 00:34:37.002238

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a6384ed4df09'
down_revision = '7bff4491b4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_question', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_question', 'image_url')
    # ### end Alembic commands ###
