"""add_image_url_to_study_knowledge_node

Revision ID: add_image_url_kn
Revises: ee163b4742be
Create Date: 2025-01-02 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'add_image_url_kn'
down_revision = 'ee163b4742be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 image_url 字段到 study_knowledge_node 表
    op.add_column('study_knowledge_node', sa.Column('image_url', sa.String(length=500), nullable=False, server_default=sa.text("''")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 image_url 字段
    op.drop_column('study_knowledge_node', 'image_url')
    # ### end Alembic commands ###








