"""add progress_question_id to study_session

Revision ID: add_progress_to_session
Revises: add_note_to_session_item
Create Date: 2025-12-23 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_progress_to_session'
down_revision = 'add_note_to_session_item'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_session', sa.Column('progress_question_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_session', 'progress_question_id')
    # ### end Alembic commands ###
