"""add note to study_session_item

Revision ID: add_note_to_session_item
Revises: add_is_favorited
Create Date: 2025-12-23 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_note_to_session_item'
down_revision = 'add_is_favorited'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_session_item', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_session_item', 'note')
    # ### end Alembic commands ###


