"""add is_favorited to study_learning_item

Revision ID: add_is_favorited
Revises: a6384ed4df09
Create Date: 2025-12-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_is_favorited'
down_revision = 'a6384ed4df09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_learning_item', sa.Column('is_favorited', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_learning_item', 'is_favorited')
    # ### end Alembic commands ###
