"""add_latitude_longitude_to_gas_station

Revision ID: c5532bf420da
Revises: a1b2c3d4e5f6
Create Date: 2025-12-29 18:51:24.521853

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5532bf420da'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 latitude 和 longitude 字段到 gas_station 表
    op.add_column('gas_station', sa.Column('latitude', sa.String(length=64), nullable=True, server_default=sa.text("''")))
    op.add_column('gas_station', sa.Column('longitude', sa.String(length=64), nullable=True, server_default=sa.text("''")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 latitude 和 longitude 字段
    op.drop_column('gas_station', 'longitude')
    op.drop_column('gas_station', 'latitude')
    # ### end Alembic commands ###
