"""create_flashcard_progress_table

Revision ID: create_flashcard_progress
Revises: add_image_url_kn
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'create_flashcard_progress'
down_revision = 'add_image_url_kn'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'study_flashcard_progress',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('session_item_id', sa.Integer(), nullable=False),
        sa.Column('exam_id', sa.Integer(), nullable=True),
        sa.Column('interval_days', sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column('next_review_date', sa.Date(), nullable=False),
        sa.Column('last_rating', sa.String(length=16), nullable=True),
        sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
        sa.Column('state', sa.String(length=16), nullable=False, server_default=sa.text("'learning'")),
        sa.Column('review_count', sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column('creator', sa.String(length=64), nullable=True),
        sa.Column('dept_id', sa.Integer(), nullable=True),
        sa.Column('updater', sa.String(length=64), nullable=True),
        sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column('create_time', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column('update_time', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"), onupdate=sa.text("CURRENT_TIMESTAMP")),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建索引
    op.create_index('ix_study_flashcard_progress_user_id', 'study_flashcard_progress', ['user_id'])
    op.create_index('ix_study_flashcard_progress_session_item_id', 'study_flashcard_progress', ['session_item_id'])
    op.create_index('ix_study_flashcard_progress_exam_id', 'study_flashcard_progress', ['exam_id'])
    op.create_index('ix_study_flashcard_progress_next_review_date', 'study_flashcard_progress', ['next_review_date'])
    op.create_index('ix_study_flashcard_progress_state', 'study_flashcard_progress', ['state'])
    op.create_index('ix_study_flashcard_progress_dept_id', 'study_flashcard_progress', ['dept_id'])
    
    # 创建唯一索引：确保 (user_id, session_item_id) 唯一
    op.create_index('ix_study_flashcard_progress_user_session_item', 'study_flashcard_progress', ['user_id', 'session_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_study_flashcard_progress_user_session_item', table_name='study_flashcard_progress')
    op.drop_index('ix_study_flashcard_progress_dept_id', table_name='study_flashcard_progress')
    op.drop_index('ix_study_flashcard_progress_state', table_name='study_flashcard_progress')
    op.drop_index('ix_study_flashcard_progress_next_review_date', table_name='study_flashcard_progress')
    op.drop_index('ix_study_flashcard_progress_exam_id', table_name='study_flashcard_progress')
    op.drop_index('ix_study_flashcard_progress_session_item_id', table_name='study_flashcard_progress')
    op.drop_index('ix_study_flashcard_progress_user_id', table_name='study_flashcard_progress')
    op.drop_table('study_flashcard_progress')
    # ### end Alembic commands ###
