"""remove_postcode_distance_from_station_add_distance_to_price

Revision ID: ee163b4742be
Revises: c5532bf420da
Create Date: 2025-12-29 18:55:40.425023

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ee163b4742be'
down_revision = 'c5532bf420da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 在 gas_price 表中添加 distance 字段
    op.add_column('gas_price', sa.Column('distance', sa.String(length=10), nullable=True, server_default=sa.text("''")))
    
    # 2. 从 gas_station 表中删除 postcode 和 distance 字段
    op.drop_column('gas_station', 'distance')
    op.drop_column('gas_station', 'postcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 恢复 gas_station 表的 postcode 和 distance 字段
    op.add_column('gas_station', sa.Column('postcode', sa.String(length=64), server_default=sa.text("''"), nullable=False))
    op.add_column('gas_station', sa.Column('distance', sa.String(length=10), server_default=sa.text("''"), nullable=False))
    
    # 删除 gas_price 表的 distance 字段
    op.drop_column('gas_price', 'distance')
    # ### end Alembic commands ###
