"""Add module master_detal_user02

Revision ID: 05c8aeab7d56
Revises: 1994ec6f6047
Create Date: 2025-07-21 11:56:37.156340

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '05c8aeab7d56'
down_revision = '1994ec6f6047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mulcurdmodelorder02',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mulcurdmodelorder02_order_code'), 'mulcurdmodelorder02', ['order_code'], unique=True)
    op.create_index(op.f('ix_mulcurdmodelorder02_user_id'), 'mulcurdmodelorder02', ['user_id'], unique=False)
    op.create_table('mulcurdmodeluser02',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('user_status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mulcurdmodeluser02_user_code'), 'mulcurdmodeluser02', ['user_code'], unique=True)
    op.create_index(op.f('ix_mulcurdmodeluser02_user_name'), 'mulcurdmodeluser02', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mulcurdmodeluser02_user_name'), table_name='mulcurdmodeluser02')
    op.drop_index(op.f('ix_mulcurdmodeluser02_user_code'), table_name='mulcurdmodeluser02')
    op.drop_table('mulcurdmodeluser02')
    op.drop_index(op.f('ix_mulcurdmodelorder02_user_id'), table_name='mulcurdmodelorder02')
    op.drop_index(op.f('ix_mulcurdmodelorder02_order_code'), table_name='mulcurdmodelorder02')
    op.drop_table('mulcurdmodelorder02')
    # ### end Alembic commands ###
