"""clean up

Revision ID: 05ce1c1194da
Revises: e2103334067f
Create Date: 2025-08-08 10:30:54.301525

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05ce1c1194da'
down_revision = 'e2103334067f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_demo_user003_dept_id', table_name='demo_user003')
    op.drop_table('demo_user003')
    op.drop_index('ix_demo_user002_dept_id', table_name='demo_user002')
    op.drop_table('demo_user002')
    op.drop_table('demo_user001')
    op.drop_table('sys_dic_data001')
    op.drop_index('ix_sub001_dept_id', table_name='sub001')
    op.drop_table('sub001')
    op.drop_index('ix_sys_dic001_dic_code', table_name='sys_dic001')
    op.drop_table('sys_dic001')
    op.drop_index('ix_main001_dept_id', table_name='main001')
    op.drop_index('ix_main001_dic_code', table_name='main001')
    op.drop_table('main001')
    op.drop_index('ix_demo_user_name', table_name='demo_user')
    op.drop_table('demo_user')
    op.drop_index('ix_main002_dept_id', table_name='main002')
    op.drop_index('ix_main002_dic_code', table_name='main002')
    op.drop_table('main002')
    op.drop_index('ix_demo_user004_dept_id', table_name='demo_user004')
    op.drop_table('demo_user004')
    op.drop_index('ix_sub002_dept_id', table_name='sub002')
    op.drop_table('sub002')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub002',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sys_dic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orderby', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sub002_pkey')
    )
    op.create_index('ix_sub002_dept_id', 'sub002', ['dept_id'], unique=False)
    op.create_table('demo_user004',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demo_user004_pkey')
    )
    op.create_index('ix_demo_user004_dept_id', 'demo_user004', ['dept_id'], unique=False)
    op.create_table('main002',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dic_code', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('dic_name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='main002_pkey')
    )
    op.create_index('ix_main002_dic_code', 'main002', ['dic_code'], unique=True)
    op.create_index('ix_main002_dept_id', 'main002', ['dept_id'], unique=False)
    op.create_table('demo_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remark', sa.VARCHAR(length=1000), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('birth_day', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hobby2', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('hobby', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('gender2', sa.VARCHAR(), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demo_user_pkey')
    )
    op.create_index('ix_demo_user_name', 'demo_user', ['name'], unique=False)
    op.create_table('main001',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dic_code', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('dic_name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='main001_pkey')
    )
    op.create_index('ix_main001_dic_code', 'main001', ['dic_code'], unique=True)
    op.create_index('ix_main001_dept_id', 'main001', ['dept_id'], unique=False)
    op.create_table('sys_dic001',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dic_code', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('dic_name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sys_dic001_pkey')
    )
    op.create_index('ix_sys_dic001_dic_code', 'sys_dic001', ['dic_code'], unique=True)
    op.create_table('sub001',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sys_dic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orderby', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sub001_pkey')
    )
    op.create_index('ix_sub001_dept_id', 'sub001', ['dept_id'], unique=False)
    op.create_table('sys_dic_data001',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sys_dic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orderby', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sys_dic_data001_pkey')
    )
    op.create_table('demo_user001',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demo_user001_pkey')
    )
    op.create_table('demo_user002',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='demo_user002_pkey')
    )
    op.create_index('ix_demo_user002_dept_id', 'demo_user002', ['dept_id'], unique=False)
    op.create_table('demo_user003',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demo_user003_pkey')
    )
    op.create_index('ix_demo_user003_dept_id', 'demo_user003', ['dept_id'], unique=False)
    # ### end Alembic commands ###
