"""demoUser add filed333

Revision ID: 0c5efd614d38
Revises: cd7865fe7427
Create Date: 2025-07-24 10:36:33.711329

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0c5efd614d38'
down_revision = 'cd7865fe7427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
