"""add user must change pwd flag

Revision ID: 0d523386b741
Revises: b770ebba907c
Create Date: 2025-08-11 14:12:33.803034

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0d523386b741'
down_revision = 'b770ebba907c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
        UPDATE "user" 
        SET must_change_password = false 
        WHERE must_change_password IS NULL
    """)    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'must_change_password')
    # ### end Alembic commands ###
