"""update fsgManage filed define

Revision ID: 0fb9c10dffb9
Revises: 35070f242cac
Create Date: 2025-09-03 14:11:11.941303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0fb9c10dffb9'
down_revision = '35070f242cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fsa_manage', sa.Column('delivery_center_type', sa.String(length=50), server_default=sa.text("''"), nullable=False))
    op.add_column('fsa_manage', sa.Column('delivery_center_name', sa.String(length=50), server_default=sa.text("''"), nullable=False))
    op.add_column('fsa_manage', sa.Column('center_number', sa.Integer(), nullable=False))
    op.drop_column('fsa_manage', 'delivery_centre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fsa_manage', sa.Column('delivery_centre', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('fsa_manage', 'center_number')
    op.drop_column('fsa_manage', 'delivery_center_name')
    op.drop_column('fsa_manage', 'delivery_center_type')
    # ### end Alembic commands ###
