"""Add module menu

Revision ID: 13e0f0fdbbaa
Revises: ece18cd6f3b5
Create Date: 2025-07-28 12:49:21.467218

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '13e0f0fdbbaa'
down_revision = 'ece18cd6f3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('code', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('icon', sa.String(length=50), server_default=sa.text("''"), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('order_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('modual_name', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_code'), 'menu', ['code'], unique=False)
    op.create_index(op.f('ix_menu_parent_id'), 'menu', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_parent_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_code'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
