"""change center_num to str

Revision ID: 179b5ec525ea
Revises: 85303098c41a
Create Date: 2025-09-04 09:55:28.253515

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '179b5ec525ea'
down_revision = '85303098c41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fsa_manage', 'center_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fsa_manage', 'center_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
