"""demoUser add filed23

Revision ID: 17d8bd6d7e01
Revises: 83e7de634ea6
Create Date: 2025-07-24 10:22:56.781125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17d8bd6d7e01'
down_revision = '83e7de634ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demouser', sa.Column('gender2', sa.String(), server_default=sa.text("'unknown'"), nullable=False))
    op.alter_column('demouser', 'remark',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('demouser', 'birth_day',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('demouser', 'hobby2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demouser', 'hobby2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('demouser', 'birth_day',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('demouser', 'remark',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.drop_column('demouser', 'gender2')
    # ### end Alembic commands ###
