"""Add module

Revision ID: 1839d8c5a5ad
Revises: c6134b253383
Create Date: 2025-07-22 10:47:06.968791

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1839d8c5a5ad'
down_revision = 'c6134b253383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
