"""Add module master_detal_user001

Revision ID: 1994ec6f6047
Revises: e168cabb5097
Create Date: 2025-07-21 11:40:46.874517

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1994ec6f6047'
down_revision = 'e168cabb5097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mulcurdmodelorder01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mulcurdmodelorder01_order_code'), 'mulcurdmodelorder01', ['order_code'], unique=True)
    op.create_index(op.f('ix_mulcurdmodelorder01_user_id'), 'mulcurdmodelorder01', ['user_id'], unique=False)
    op.create_table('mulcurdmodeluser01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('user_status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mulcurdmodeluser01_user_code'), 'mulcurdmodeluser01', ['user_code'], unique=True)
    op.create_index(op.f('ix_mulcurdmodeluser01_user_name'), 'mulcurdmodeluser01', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mulcurdmodeluser01_user_name'), table_name='mulcurdmodeluser01')
    op.drop_index(op.f('ix_mulcurdmodeluser01_user_code'), table_name='mulcurdmodeluser01')
    op.drop_table('mulcurdmodeluser01')
    op.drop_index(op.f('ix_mulcurdmodelorder01_user_id'), table_name='mulcurdmodelorder01')
    op.drop_index(op.f('ix_mulcurdmodelorder01_order_code'), table_name='mulcurdmodelorder01')
    op.drop_table('mulcurdmodelorder01')
    # ### end Alembic commands ###
