"""set predict_quantity default value is -1, to distinguish it from 0

Revision ID: 227a659b5112
Revises: ca8f3951336f
Create Date: 2025-08-20 10:37:38.488950

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '227a659b5112'
down_revision = 'ca8f3951336f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
