"""Add module master_detal_user03

Revision ID: 2634befc1f82
Revises: 05c8aeab7d56
Create Date: 2025-07-21 12:22:41.769940

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2634befc1f82'
down_revision = '05c8aeab7d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mulcurdmodelorder03',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mulcurdmodelorder03_order_code'), 'mulcurdmodelorder03', ['order_code'], unique=True)
    op.create_index(op.f('ix_mulcurdmodelorder03_user_id'), 'mulcurdmodelorder03', ['user_id'], unique=False)
    op.create_table('mulcurdmodeluser03',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('user_status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mulcurdmodeluser03_user_code'), 'mulcurdmodeluser03', ['user_code'], unique=True)
    op.create_index(op.f('ix_mulcurdmodeluser03_user_name'), 'mulcurdmodeluser03', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mulcurdmodeluser03_user_name'), table_name='mulcurdmodeluser03')
    op.drop_index(op.f('ix_mulcurdmodeluser03_user_code'), table_name='mulcurdmodeluser03')
    op.drop_table('mulcurdmodeluser03')
    op.drop_index(op.f('ix_mulcurdmodelorder03_user_id'), table_name='mulcurdmodelorder03')
    op.drop_index(op.f('ix_mulcurdmodelorder03_order_code'), table_name='mulcurdmodelorder03')
    op.drop_table('mulcurdmodelorder03')
    # ### end Alembic commands ###
