"""add user dept_id

Revision ID: 2a23fc97513c
Revises: 59541ba91a32
Create Date: 2025-08-06 16:34:16.168772

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2a23fc97513c'
down_revision = '59541ba91a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dept_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_dept_id'), 'user', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_dept_id'), table_name='user')
    op.drop_column('user', 'dept_id')
    # ### end Alembic commands ###
