"""Add module user order, for Master-Detail

Revision ID: 2f29b7e445b2
Revises: c130396f0492
Create Date: 2025-07-17 15:19:51.917356

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2f29b7e445b2'
down_revision = 'c130396f0492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mulcurdmodelorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mulcurdmodelorder_order_code'), 'mulcurdmodelorder', ['order_code'], unique=True)
    op.create_index(op.f('ix_mulcurdmodelorder_user_id'), 'mulcurdmodelorder', ['user_id'], unique=True)
    op.create_table('mulcurdmodeluser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('user_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('user_status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mulcurdmodeluser_user_code'), 'mulcurdmodeluser', ['user_code'], unique=True)
    op.create_index(op.f('ix_mulcurdmodeluser_user_name'), 'mulcurdmodeluser', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mulcurdmodeluser_user_name'), table_name='mulcurdmodeluser')
    op.drop_index(op.f('ix_mulcurdmodeluser_user_code'), table_name='mulcurdmodeluser')
    op.drop_table('mulcurdmodeluser')
    op.drop_index(op.f('ix_mulcurdmodelorder_user_id'), table_name='mulcurdmodelorder')
    op.drop_index(op.f('ix_mulcurdmodelorder_order_code'), table_name='mulcurdmodelorder')
    op.drop_table('mulcurdmodelorder')
    # ### end Alembic commands ###
