"""update role_dept_link

Revision ID: 2f3ac6e06f13
Revises: cb1e320f6324
Create Date: 2025-08-05 15:53:33.335173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2f3ac6e06f13'
down_revision = 'cb1e320f6324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_dept_link',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'dept_id')
    )
    op.drop_table('role_shop_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_shop_link',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'shop_id', name='role_shop_link_pkey')
    )
    op.drop_table('role_dept_link')
    # ### end Alembic commands ###
