"""add fsgManage

Revision ID: 35070f242cac
Revises: ac0bef0e94e9
Create Date: 2025-09-03 13:59:13.482025

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '35070f242cac'
down_revision = 'ac0bef0e94e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fsa_manage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fsa', sa.String(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('delivery_centre', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('city', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('province', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fsa')
    )
    op.create_index(op.f('ix_fsa_manage_dept_id'), 'fsa_manage', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fsa_manage_dept_id'), table_name='fsa_manage')
    op.drop_table('fsa_manage')
    # ### end Alembic commands ###
