"""add quotesToScrape module

Revision ID: 3799a0de4af5
Revises: 991de161253e
Create Date: 2025-08-26 12:23:48.960360

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3799a0de4af5'
down_revision = '991de161253e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes_to_scrape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), server_default=sa.text("''"), nullable=False),
    sa.Column('author', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('tags', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('author_birthday', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('author_location', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('author_bio', sa.String(length=2000), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_to_scrape_author'), 'quotes_to_scrape', ['author'], unique=False)
    op.create_index(op.f('ix_quotes_to_scrape_dept_id'), 'quotes_to_scrape', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_to_scrape_dept_id'), table_name='quotes_to_scrape')
    op.drop_index(op.f('ix_quotes_to_scrape_author'), table_name='quotes_to_scrape')
    op.drop_table('quotes_to_scrape')
    # ### end Alembic commands ###
