"""add sephrao product

Revision ID: 3d7697420efd
Revises: d30268943f1f
Create Date: 2025-08-14 10:35:49.371166

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3d7697420efd'
down_revision = 'd30268943f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product4_sephora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productId', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('skuId', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('productName', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('listPrice', sa.String(length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('variationType', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('variationTypeDisplayName', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('variationValue', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('images', sa.String(length=10000), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product4_sephora_dept_id'), 'product4_sephora', ['dept_id'], unique=False)
    op.create_index(op.f('ix_product4_sephora_productId'), 'product4_sephora', ['productId'], unique=False)
    op.create_index(op.f('ix_product4_sephora_skuId'), 'product4_sephora', ['skuId'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product4_sephora_skuId'), table_name='product4_sephora')
    op.drop_index(op.f('ix_product4_sephora_productId'), table_name='product4_sephora')
    op.drop_index(op.f('ix_product4_sephora_dept_id'), table_name='product4_sephora')
    op.drop_table('product4_sephora')
    # ### end Alembic commands ###
