"""add translate name filed in table flyer_details

Revision ID: 3dcd59aaaba0
Revises: c7a95007abd6
Create Date: 2025-09-04 14:04:23.144603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3dcd59aaaba0'
down_revision = 'c7a95007abd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flyer_details', sa.Column('cn_name', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('flyer_details', sa.Column('hk_name', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flyer_details', 'hk_name')
    op.drop_column('flyer_details', 'cn_name')
    # ### end Alembic commands ###
