"""add main-sub001

Revision ID: 45371caa225c
Revises: 5404933d5f41
Create Date: 2025-08-07 15:42:42.151909

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '45371caa225c'
down_revision = '5404933d5f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main001',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dic_code', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('dic_name', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main001_dept_id'), 'main001', ['dept_id'], unique=False)
    op.create_index(op.f('ix_main001_dic_code'), 'main001', ['dic_code'], unique=True)
    op.create_table('sub001',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sys_dic_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('value', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('orderby', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=200), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub001_dept_id'), 'sub001', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub001_dept_id'), table_name='sub001')
    op.drop_table('sub001')
    op.drop_index(op.f('ix_main001_dic_code'), table_name='main001')
    op.drop_index(op.f('ix_main001_dept_id'), table_name='main001')
    op.drop_table('main001')
    # ### end Alembic commands ###
