"""update brand filed length

Revision ID: 4c2b145908a9
Revises: f6f0e71e9352
Create Date: 2025-09-10 12:27:53.629061

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4c2b145908a9'
down_revision = 'f6f0e71e9352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand', 'en_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('brand', 'cn_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=510),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('brand', 'hk_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=510),
               existing_nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('brand', 'original_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand', 'original_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('brand', 'hk_name',
               existing_type=sa.String(length=510),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('brand', 'cn_name',
               existing_type=sa.String(length=510),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('brand', 'en_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
