"""Add module crudModel001

Revision ID: 4ebc056bc815
Revises: c3ddabf7024d
Create Date: 2025-07-16 11:47:22.512640

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4ebc056bc815'
down_revision = 'c3ddabf7024d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curdmodel001',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curdmodel001_code'), 'curdmodel001', ['code'], unique=True)
    op.create_index(op.f('ix_curdmodel001_name'), 'curdmodel001', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curdmodel001_name'), table_name='curdmodel001')
    op.drop_index(op.f('ix_curdmodel001_code'), table_name='curdmodel001')
    op.drop_table('curdmodel001')
    # ### end Alembic commands ###
