"""add demoUser003

Revision ID: 5404933d5f41
Revises: 2a23fc97513c
Create Date: 2025-08-07 15:11:08.963401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5404933d5f41'
down_revision = '2a23fc97513c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_user003',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_user003_dept_id'), 'demo_user003', ['dept_id'], unique=False)
    op.create_index(op.f('ix_demo_user002_dept_id'), 'demo_user002', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_user002_dept_id'), table_name='demo_user002')
    op.drop_index(op.f('ix_demo_user003_dept_id'), table_name='demo_user003')
    op.drop_table('demo_user003')
    # ### end Alembic commands ###
