"""add demoUser002 dept_id for data permission demo

Revision ID: 59541ba91a32
Revises: 2f3ac6e06f13
Create Date: 2025-08-06 16:22:51.963650

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59541ba91a32'
down_revision = '2f3ac6e06f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_user002', sa.Column('dept_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo_user002', 'dept_id')
    # ### end Alembic commands ###
