"""add field predict_quantity

Revision ID: 5c47dd2635d9
Revises: c0135bb1550f
Create Date: 2025-08-18 14:05:57.247509

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5c47dd2635d9'
down_revision = 'c0135bb1550f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_predict', sa.Column('predict_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_predict', 'predict_quantity')
    # ### end Alembic commands ###
