"""update module menu

Revision ID: 5e4f74a35904
Revises: 13e0f0fdbbaa
Create Date: 2025-07-30 10:39:39.072559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5e4f74a35904'
down_revision = '13e0f0fdbbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('menu_label', sa.String(length=50), server_default=sa.text("''"), nullable=False))
    op.add_column('menu', sa.Column('permission_code', sa.String(length=100), server_default=sa.text("''"), nullable=False))
    op.add_column('menu', sa.Column('module_code', sa.String(length=50), server_default=sa.text("''"), nullable=False))
    op.drop_index('ix_menu_code', table_name='menu')
    op.create_index(op.f('ix_menu_permission_code'), 'menu', ['permission_code'], unique=False)
    op.drop_column('menu', 'code')
    op.drop_column('menu', 'name')
    op.drop_column('menu', 'modual_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('modual_name', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('name', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('menu', sa.Column('code', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_menu_permission_code'), table_name='menu')
    op.create_index('ix_menu_code', 'menu', ['code'], unique=False)
    op.drop_column('menu', 'module_code')
    op.drop_column('menu', 'permission_code')
    op.drop_column('menu', 'menu_label')
    # ### end Alembic commands ###
