"""add demo

Revision ID: 61ae8a2d1ad1
Revises: 293be2b787d4
Create Date: 2025-08-08 11:33:37.673575

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '61ae8a2d1ad1'
down_revision = '293be2b787d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_order01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('open_date', sa.String(), nullable=True),
    sa.Column('order_status', sa.String(length=128), server_default=sa.text("'enabled'"), nullable=False),
    sa.Column('open_function', sa.String(), server_default=sa.text("'None'"), nullable=True),
    sa.Column('order_info', sa.String(length=1000), server_default=sa.text("''"), nullable=True),
    sa.Column('aaa', sa.String(length=222), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_order01_dept_id'), 'demo_order01', ['dept_id'], unique=False)
    op.create_index(op.f('ix_demo_order01_order_code'), 'demo_order01', ['order_code'], unique=True)
    op.create_table('main002',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dic_code', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('dic_name', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main002_dept_id'), 'main002', ['dept_id'], unique=False)
    op.create_index(op.f('ix_main002_dic_code'), 'main002', ['dic_code'], unique=True)
    op.create_table('sub002',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sys_dic_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('value', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('orderby', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=200), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub002_dept_id'), 'sub002', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub002_dept_id'), table_name='sub002')
    op.drop_table('sub002')
    op.drop_index(op.f('ix_main002_dic_code'), table_name='main002')
    op.drop_index(op.f('ix_main002_dept_id'), table_name='main002')
    op.drop_table('main002')
    op.drop_index(op.f('ix_demo_order01_order_code'), table_name='demo_order01')
    op.drop_index(op.f('ix_demo_order01_dept_id'), table_name='demo_order01')
    op.drop_table('demo_order01')
    # ### end Alembic commands ###
