"""add crud module

Revision ID: 620cda713296
Revises: 2634befc1f82
Create Date: 2025-07-21 15:27:26.078054

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '620cda713296'
down_revision = '2634befc1f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crud_define_filed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('form_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('max_length', sa.Integer(), nullable=False),
    sa.Column('default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required', sa.Integer(), nullable=True),
    sa.Column('insertable', sa.Integer(), nullable=True),
    sa.Column('updatable', sa.Integer(), nullable=True),
    sa.Column('listable', sa.Integer(), nullable=True),
    sa.Column('queryable', sa.Integer(), nullable=True),
    sa.Column('sortable', sa.Integer(), nullable=True),
    sa.Column('primary_key', sa.Integer(), nullable=True),
    sa.Column('nullable', sa.Integer(), nullable=True),
    sa.Column('unique', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crud_define_filed_default'), 'crud_define_filed', ['default'], unique=False)
    op.create_index(op.f('ix_crud_define_filed_description'), 'crud_define_filed', ['description'], unique=False)
    op.create_index(op.f('ix_crud_define_filed_max_length'), 'crud_define_filed', ['max_length'], unique=False)
    op.create_index(op.f('ix_crud_define_filed_module_id'), 'crud_define_filed', ['module_id'], unique=False)
    op.create_index(op.f('ix_crud_define_filed_name'), 'crud_define_filed', ['name'], unique=False)
    op.create_index(op.f('ix_crud_define_filed_options'), 'crud_define_filed', ['options'], unique=False)
    op.create_table('crud_define_moduel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crud_define_moduel_label'), 'crud_define_moduel', ['label'], unique=True)
    op.create_index(op.f('ix_crud_define_moduel_module_name'), 'crud_define_moduel', ['module_name'], unique=True)
    op.drop_index('ix_appnew5_code', table_name='appnew5')
    op.drop_index('ix_appnew5_name', table_name='appnew5')
    op.drop_table('appnew5')
    op.drop_index('ix_appnew2_name', table_name='appnew2')
    op.drop_table('appnew2')
    op.drop_index('ix_curdmodel001_code', table_name='curdmodel001')
    op.drop_index('ix_curdmodel001_name', table_name='curdmodel001')
    op.drop_table('curdmodel001')
    op.drop_index('ix_appnew4_name', table_name='appnew4')
    op.drop_table('appnew4')
    op.drop_index('ix_mulcurdmodeluser02_user_code', table_name='mulcurdmodeluser02')
    op.drop_index('ix_mulcurdmodeluser02_user_name', table_name='mulcurdmodeluser02')
    op.drop_table('mulcurdmodeluser02')
    op.drop_index('ix_appnew_name', table_name='appnew')
    op.drop_table('appnew')
    op.drop_index('ix_appnew3_name', table_name='appnew3')
    op.drop_table('appnew3')
    op.drop_index('ix_mulcurdmodelorder02_order_code', table_name='mulcurdmodelorder02')
    op.drop_index('ix_mulcurdmodelorder02_user_id', table_name='mulcurdmodelorder02')
    op.drop_table('mulcurdmodelorder02')
    op.drop_index('ix_mulcurdmodeluser_user_code', table_name='mulcurdmodeluser')
    op.drop_index('ix_mulcurdmodeluser_user_name', table_name='mulcurdmodeluser')
    op.drop_table('mulcurdmodeluser')
    op.drop_index('ix_mulcurdmodelorder01_order_code', table_name='mulcurdmodelorder01')
    op.drop_index('ix_mulcurdmodelorder01_user_id', table_name='mulcurdmodelorder01')
    op.drop_table('mulcurdmodelorder01')
    op.drop_index('ix_mulcurdmodeluser01_user_code', table_name='mulcurdmodeluser01')
    op.drop_index('ix_mulcurdmodeluser01_user_name', table_name='mulcurdmodeluser01')
    op.drop_table('mulcurdmodeluser01')
    op.drop_index('ix_mulcurdmodelorder_order_code', table_name='mulcurdmodelorder')
    op.drop_index('ix_mulcurdmodelorder_user_id', table_name='mulcurdmodelorder')
    op.drop_table('mulcurdmodelorder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mulcurdmodelorder',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mulcurdmodelorder_pkey')
    )
    op.create_index('ix_mulcurdmodelorder_user_id', 'mulcurdmodelorder', ['user_id'], unique=False)
    op.create_index('ix_mulcurdmodelorder_order_code', 'mulcurdmodelorder', ['order_code'], unique=True)
    op.create_table('mulcurdmodeluser01',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mulcurdmodeluser01_pkey')
    )
    op.create_index('ix_mulcurdmodeluser01_user_name', 'mulcurdmodeluser01', ['user_name'], unique=False)
    op.create_index('ix_mulcurdmodeluser01_user_code', 'mulcurdmodeluser01', ['user_code'], unique=True)
    op.create_table('mulcurdmodelorder01',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mulcurdmodelorder01_pkey')
    )
    op.create_index('ix_mulcurdmodelorder01_user_id', 'mulcurdmodelorder01', ['user_id'], unique=False)
    op.create_index('ix_mulcurdmodelorder01_order_code', 'mulcurdmodelorder01', ['order_code'], unique=True)
    op.create_table('mulcurdmodeluser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mulcurdmodeluser_pkey')
    )
    op.create_index('ix_mulcurdmodeluser_user_name', 'mulcurdmodeluser', ['user_name'], unique=True)
    op.create_index('ix_mulcurdmodeluser_user_code', 'mulcurdmodeluser', ['user_code'], unique=True)
    op.create_table('mulcurdmodelorder02',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mulcurdmodelorder02_pkey')
    )
    op.create_index('ix_mulcurdmodelorder02_user_id', 'mulcurdmodelorder02', ['user_id'], unique=False)
    op.create_index('ix_mulcurdmodelorder02_order_code', 'mulcurdmodelorder02', ['order_code'], unique=True)
    op.create_table('appnew3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('app_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('app_secret', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='appnew3_pkey'),
    sa.UniqueConstraint('code', name='appnew3_code_key')
    )
    op.create_index('ix_appnew3_name', 'appnew3', ['name'], unique=False)
    op.create_table('appnew',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('app_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('app_secret', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='appnew_pkey'),
    sa.UniqueConstraint('code', name='appnew_code_key')
    )
    op.create_index('ix_appnew_name', 'appnew', ['name'], unique=False)
    op.create_table('mulcurdmodeluser02',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mulcurdmodeluser02_pkey')
    )
    op.create_index('ix_mulcurdmodeluser02_user_name', 'mulcurdmodeluser02', ['user_name'], unique=False)
    op.create_index('ix_mulcurdmodeluser02_user_code', 'mulcurdmodeluser02', ['user_code'], unique=True)
    op.create_table('appnew4',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('app_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('app_secret', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='appnew4_pkey'),
    sa.UniqueConstraint('code', name='appnew4_code_key')
    )
    op.create_index('ix_appnew4_name', 'appnew4', ['name'], unique=False)
    op.create_table('curdmodel001',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='curdmodel001_pkey')
    )
    op.create_index('ix_curdmodel001_name', 'curdmodel001', ['name'], unique=True)
    op.create_index('ix_curdmodel001_code', 'curdmodel001', ['code'], unique=True)
    op.create_table('appnew2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('app_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('app_secret', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='appnew2_pkey'),
    sa.UniqueConstraint('code', name='appnew2_code_key')
    )
    op.create_index('ix_appnew2_name', 'appnew2', ['name'], unique=False)
    op.create_table('appnew5',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('app_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('app_secret', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='appnew5_pkey')
    )
    op.create_index('ix_appnew5_name', 'appnew5', ['name'], unique=True)
    op.create_index('ix_appnew5_code', 'appnew5', ['code'], unique=True)
    op.drop_index(op.f('ix_crud_define_moduel_module_name'), table_name='crud_define_moduel')
    op.drop_index(op.f('ix_crud_define_moduel_label'), table_name='crud_define_moduel')
    op.drop_table('crud_define_moduel')
    op.drop_index(op.f('ix_crud_define_filed_options'), table_name='crud_define_filed')
    op.drop_index(op.f('ix_crud_define_filed_name'), table_name='crud_define_filed')
    op.drop_index(op.f('ix_crud_define_filed_module_id'), table_name='crud_define_filed')
    op.drop_index(op.f('ix_crud_define_filed_max_length'), table_name='crud_define_filed')
    op.drop_index(op.f('ix_crud_define_filed_description'), table_name='crud_define_filed')
    op.drop_index(op.f('ix_crud_define_filed_default'), table_name='crud_define_filed')
    op.drop_table('crud_define_filed')
    # ### end Alembic commands ###
