"""update module

Revision ID: 7a2f5da1363c
Revises: b45bf0fd3181
Create Date: 2025-07-22 15:33:34.925514

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7a2f5da1363c'
down_revision = 'b45bf0fd3181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demoorder01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('open_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_info', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demoorder01_order_code'), 'demoorder01', ['order_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demoorder01_order_code'), table_name='demoorder01')
    op.drop_table('demoorder01')
    # ### end Alembic commands ###
