"""update fsgManage filed define 01

Revision ID: 7f8d39348aaf
Revises: 0fb9c10dffb9
Create Date: 2025-09-03 14:15:26.822518

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f8d39348aaf'
down_revision = '0fb9c10dffb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fsa_manage', 'center_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fsa_manage', 'center_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
