"""demoUser add filed23

Revision ID: 83e7de634ea6
Revises: cf11a8a1f51a
Create Date: 2025-07-24 10:10:55.481228

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83e7de634ea6'
down_revision = 'cf11a8a1f51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demouser', sa.Column('gender2', sa.String(), server_default=sa.text("'unknown'"), nullable=False))
    op.alter_column('demouser', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('demouser', 'birth_day',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('demouser', 'birth_day',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('demouser', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('demouser', 'gender2')
    # ### end Alembic commands ###
