"""add length for flyer details

Revision ID: 85303098c41a
Revises: a38e14706de0
Create Date: 2025-09-03 15:29:58.079724

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '85303098c41a'
down_revision = 'a38e14706de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flyer_details', 'brand',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'cutout_image_url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'merchant',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flyer_details', 'merchant',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'cutout_image_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'brand',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
