"""add es_deal_flog filed

Revision ID: 8b1f2c5f1c73
Revises: d624268e1dec
Create Date: 2025-09-07 13:46:55.961270

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8b1f2c5f1c73'
down_revision = 'd624268e1dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 添加新列
    op.add_column('flyer_details', sa.Column('es_deal_flag', sa.Boolean(), server_default='false', nullable=True))

    # 2. 删除原先的唯一约束（而不是索引）
    op.drop_constraint('fsa_manage_fsa_key', 'fsa_manage', type_='unique')

    # 3. 创建新的唯一约束（如果不指定名字，Alembic/SQLAlchemy 会生成）
    op.create_unique_constraint(None, 'fsa_manage', ['fsa'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 删除新约束
    op.drop_constraint(None, 'fsa_manage', type_='unique')

    # 2. 恢复原约束（名字必须和原来一致）
    op.create_unique_constraint('fsa_manage_fsa_key', 'fsa_manage', ['fsa'])

    # 3. 删除新列
    op.drop_column('flyer_details', 'es_deal_flag')
    # ### end Alembic commands ###
