"""Add module

Revision ID: 92d48a895e05
Revises: cfc9ca09316e
Create Date: 2025-07-22 11:19:04.994330

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '92d48a895e05'
down_revision = 'cfc9ca09316e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
