"""add salepredict

Revision ID: 95ea25fdb4a2
Revises: 3d7697420efd
Create Date: 2025-08-18 12:02:16.093118

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '95ea25fdb4a2'
down_revision = '3d7697420efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_predict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_year', sa.Integer(), nullable=False),
    sa.Column('stat_month', sa.Integer(), nullable=False),
    sa.Column('shop_no', sa.String(length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('sales_quantity', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_predict_dept_id'), 'sale_predict', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_predict_dept_id'), table_name='sale_predict')
    op.drop_table('sale_predict')
    # ### end Alembic commands ###
