"""3 set predict_quantity default value is -1, to distinguish it from 0

Revision ID: 991de161253e
Revises: ca121a52726d
Create Date: 2025-08-20 10:41:08.217588

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '991de161253e'
down_revision = 'ca121a52726d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
