"""update table name

Revision ID: 9bd4ef5e5e8f
Revises: c2b979eca87e
Create Date: 2025-07-24 14:26:18.262602

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bd4ef5e5e8f'
down_revision = 'c2b979eca87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=1000), server_default=sa.text("''"), nullable=False),
    sa.Column('birth_day', sa.String(), nullable=True),
    sa.Column('hobby2', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('hobby', sa.String(), server_default=sa.text("''"), nullable=True),
    sa.Column('gender2', sa.String(), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_user_name'), 'demo_user', ['name'], unique=False)
    op.drop_index('ix_demouser_name', table_name='demouser')
    op.drop_table('demouser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demouser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remark', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('birth_day', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hobby', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hobby2', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('gender2', sa.VARCHAR(), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demouser_pkey')
    )
    op.create_index('ix_demouser_name', 'demouser', ['name'], unique=False)
    op.drop_index(op.f('ix_demo_user_name'), table_name='demo_user')
    op.drop_table('demo_user')
    # ### end Alembic commands ###
