"""remove filed shop_no in sale_predict

Revision ID: 9e7c5bf50a28
Revises: 5c47dd2635d9
Create Date: 2025-08-18 15:58:27.387880

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9e7c5bf50a28'
down_revision = '5c47dd2635d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_predict', 'sku',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('sale_predict', 'shop_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_predict', sa.Column('shop_no', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.alter_column('sale_predict', 'sku',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
