"""Add shopreportstat

Revision ID: a059d185bffb
Revises: 26af1c74baa2
Create Date: 2025-06-16 11:05:33.527693

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a059d185bffb'
down_revision = '26af1c74baa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_daily_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('pv', sa.Integer(), nullable=False),
    sa.Column('uv', sa.Integer(), nullable=False),
    sa.Column('sales_volume', sa.Integer(), nullable=False),
    sa.Column('sales_amount', sa.Float(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_daily_stat_shop_id'), 'shop_daily_stat', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_daily_stat_shop_id'), table_name='shop_daily_stat')
    op.drop_table('shop_daily_stat')
    # ### end Alembic commands ###
