"""add fsaFlyerLink

Revision ID: a38e14706de0
Revises: 7f8d39348aaf
Create Date: 2025-09-03 15:08:08.183847

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a38e14706de0'
down_revision = '7f8d39348aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fsa_flyer_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flyer_id', sa.Integer(), nullable=False),
    sa.Column('fsa', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fsa_flyer_link_dept_id'), 'fsa_flyer_link', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fsa_flyer_link_dept_id'), table_name='fsa_flyer_link')
    op.drop_table('fsa_flyer_link')
    # ### end Alembic commands ###
