"""add flyer details filed

Revision ID: ac0bef0e94e9
Revises: dd5e8663daaf
Create Date: 2025-09-02 16:44:39.035032

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ac0bef0e94e9'
down_revision = 'dd5e8663daaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flyer_details', sa.Column('merchant_id', sa.Integer(), nullable=False))
    op.add_column('flyer_details', sa.Column('merchant', sa.String(length=100), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flyer_details', 'merchant')
    op.drop_column('flyer_details', 'merchant_id')
    # ### end Alembic commands ###
