"""Add module appNew5

Revision ID: ac8cd674fd2b
Revises: 461d1c51b9c2
Create Date: 2025-07-14 16:44:35.475029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ac8cd674fd2b'
down_revision = '461d1c51b9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appnew5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('api_base_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('app_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('app_secret', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appnew5_code'), 'appnew5', ['code'], unique=True)
    op.create_index(op.f('ix_appnew5_name'), 'appnew5', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appnew5_name'), table_name='appnew5')
    op.drop_index(op.f('ix_appnew5_code'), table_name='appnew5')
    op.drop_table('appnew5')
    # ### end Alembic commands ###
