"""update module

Revision ID: b45bf0fd3181
Revises: 92d48a895e05
Create Date: 2025-07-22 11:42:12.875454

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b45bf0fd3181'
down_revision = '92d48a895e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cruddefinefileds_description', table_name='cruddefinefileds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cruddefinefileds_description', 'cruddefinefileds', ['description'], unique=False)
    # ### end Alembic commands ###
