"""add parent_menu_id

Revision ID: b97186182b42
Revises: 45371caa225c
Create Date: 2025-08-07 16:50:52.790445

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b97186182b42'
down_revision = '45371caa225c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cruddefinemoduel', sa.Column('parent_menu_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cruddefinemoduel_parent_menu_id'), 'cruddefinemoduel', ['parent_menu_id'], unique=False)
    op.add_column('masterdetailrel', sa.Column('parent_menu_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_masterdetailrel_parent_menu_id'), 'masterdetailrel', ['parent_menu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_masterdetailrel_parent_menu_id'), table_name='masterdetailrel')
    op.drop_column('masterdetailrel', 'parent_menu_id')
    op.drop_index(op.f('ix_cruddefinemoduel_parent_menu_id'), table_name='cruddefinemoduel')
    op.drop_column('cruddefinemoduel', 'parent_menu_id')
    # ### end Alembic commands ###
