"""initial

Revision ID: badca344f590
Revises: 
Create Date: 2025-11-10 21:13:53.751361

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'badca344f590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('api_base_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('app_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('app_secret', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_app_name'), 'app', ['name'], unique=False)
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en_name', sa.String(length=500), server_default=sa.text("''"), nullable=False),
    sa.Column('cn_name', sa.String(length=510), server_default=sa.text("''"), nullable=False),
    sa.Column('hk_name', sa.String(length=510), server_default=sa.text("''"), nullable=True),
    sa.Column('original_name', sa.String(length=500), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_dept_id'), 'brand', ['dept_id'], unique=False)
    op.create_table('cruddefinefileds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('primary_key', sa.Boolean(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('form_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('default', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('insertable', sa.Boolean(), nullable=True),
    sa.Column('updatable', sa.Boolean(), nullable=True),
    sa.Column('listable', sa.Boolean(), nullable=True),
    sa.Column('queryable', sa.Boolean(), nullable=True),
    sa.Column('query_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sortable', sa.Boolean(), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=True),
    sa.Column('index', sa.Boolean(), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruddefinefileds_default'), 'cruddefinefileds', ['default'], unique=False)
    op.create_index(op.f('ix_cruddefinefileds_max_length'), 'cruddefinefileds', ['max_length'], unique=False)
    op.create_index(op.f('ix_cruddefinefileds_module_id'), 'cruddefinefileds', ['module_id'], unique=False)
    op.create_index(op.f('ix_cruddefinefileds_name'), 'cruddefinefileds', ['name'], unique=False)
    op.create_table('cruddefinemoduel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('parent_menu_id', sa.Integer(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruddefinemoduel_label'), 'cruddefinemoduel', ['label'], unique=True)
    op.create_index(op.f('ix_cruddefinemoduel_module_name'), 'cruddefinemoduel', ['module_name'], unique=True)
    op.create_index(op.f('ix_cruddefinemoduel_parent_menu_id'), 'cruddefinemoduel', ['parent_menu_id'], unique=False)
    op.create_table('demo_order01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('open_date', sa.String(), nullable=True),
    sa.Column('order_status', sa.String(length=128), server_default=sa.text("'enabled'"), nullable=False),
    sa.Column('open_function', sa.String(), server_default=sa.text("'None'"), nullable=True),
    sa.Column('order_info', sa.String(length=1000), server_default=sa.text("''"), nullable=True),
    sa.Column('aaa', sa.String(length=222), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_order01_dept_id'), 'demo_order01', ['dept_id'], unique=False)
    op.create_index(op.f('ix_demo_order01_order_code'), 'demo_order01', ['order_code'], unique=True)
    op.create_table('dept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('dept_name', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('orderby', sa.Integer(), nullable=False),
    sa.Column('leader_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flipp_merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('merchant_logo', sa.String(length=250), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flipp_merchant_dept_id'), 'flipp_merchant', ['dept_id'], unique=False)
    op.create_table('flyer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), server_default=sa.text("''"), nullable=False),
    sa.Column('brand', sa.String(length=500), server_default=sa.text("''"), nullable=False),
    sa.Column('valid_from', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('valid_to', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('available_to', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('cutout_image_url', sa.String(length=500), server_default=sa.text("''"), nullable=False),
    sa.Column('price', sa.String(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('flyer_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=500), server_default=sa.text("''"), nullable=False),
    sa.Column('cn_name', sa.String(length=500), server_default=sa.text("''"), nullable=True),
    sa.Column('hk_name', sa.String(length=500), server_default=sa.text("''"), nullable=True),
    sa.Column('es_deal_flag', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flyer_details_dept_id'), 'flyer_details', ['dept_id'], unique=False)
    op.create_table('flyer_main',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('valid_from', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('valid_to', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('categories', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('fly_id', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flyer_main_dept_id'), 'flyer_main', ['dept_id'], unique=False)
    op.create_table('fsa_flyer_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flyer_id', sa.Integer(), nullable=False),
    sa.Column('fsa', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fsa_flyer_link_dept_id'), 'fsa_flyer_link', ['dept_id'], unique=False)
    op.create_table('fsa_manage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fsa', sa.String(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('delivery_center_type', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('city', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('province', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('delivery_center_name', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('center_number', sa.String(length=50), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fsa')
    )
    op.create_index(op.f('ix_fsa_manage_dept_id'), 'fsa_manage', ['dept_id'], unique=False)
    op.create_table('main002',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dic_code', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('dic_name', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main002_dept_id'), 'main002', ['dept_id'], unique=False)
    op.create_index(op.f('ix_main002_dic_code'), 'main002', ['dic_code'], unique=True)
    op.create_table('masterdetailrel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_menu_id', sa.Integer(), nullable=True),
    sa.Column('master_module_id', sa.Integer(), nullable=False),
    sa.Column('detail_module_id', sa.Integer(), nullable=False),
    sa.Column('rel_filed_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masterdetailrel_detail_module_id'), 'masterdetailrel', ['detail_module_id'], unique=False)
    op.create_index(op.f('ix_masterdetailrel_master_module_id'), 'masterdetailrel', ['master_module_id'], unique=False)
    op.create_index(op.f('ix_masterdetailrel_parent_menu_id'), 'masterdetailrel', ['parent_menu_id'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('menu_label', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('permission_code', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('icon', sa.String(length=50), server_default=sa.text("''"), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('order_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_parent_id'), 'menu', ['parent_id'], unique=False)
    op.create_index(op.f('ix_menu_permission_code'), 'menu', ['permission_code'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=True)
    op.create_table('product4_sephora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productId', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('skuId', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('productName', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('listPrice', sa.String(length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('variationType', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('variationTypeDisplayName', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('variationValue', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('images', sa.String(length=10000), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product4_sephora_dept_id'), 'product4_sephora', ['dept_id'], unique=False)
    op.create_index(op.f('ix_product4_sephora_productId'), 'product4_sephora', ['productId'], unique=False)
    op.create_index(op.f('ix_product4_sephora_skuId'), 'product4_sephora', ['skuId'], unique=True)
    op.create_table('quotes_to_scrape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=5000), server_default=sa.text("''"), nullable=False),
    sa.Column('author', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('tags', sa.String(length=500), server_default=sa.text("''"), nullable=False),
    sa.Column('author_birthday', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('author_location', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('author_bio', sa.String(length=5000), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_to_scrape_author'), 'quotes_to_scrape', ['author'], unique=False)
    op.create_index(op.f('ix_quotes_to_scrape_dept_id'), 'quotes_to_scrape', ['dept_id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('data_scope', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_code'), 'role', ['code'], unique=True)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('role_dept_link',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'dept_id')
    )
    op.create_table('role_permission_link',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sale_predict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_year', sa.Integer(), nullable=False),
    sa.Column('stat_month', sa.Integer(), nullable=False),
    sa.Column('sales_quantity', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=20), server_default=sa.text("''"), nullable=False),
    sa.Column('predict_quantity', sa.Integer(), server_default=sa.text('-1'), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_predict_dept_id'), 'sale_predict', ['dept_id'], unique=False)
    op.create_index(op.f('ix_sale_predict_sku'), 'sale_predict', ['sku'], unique=False)
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_shop_app_code'), 'shop', ['app_code'], unique=False)
    op.create_table('shop_daily_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('pv', sa.Integer(), nullable=False),
    sa.Column('uv', sa.Integer(), nullable=False),
    sa.Column('sales_volume', sa.Integer(), nullable=False),
    sa.Column('sales_amount', sa.Float(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_daily_stat_shop_id'), 'shop_daily_stat', ['shop_id'], unique=False)
    op.create_table('sub002',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sys_dic_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('value', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('orderby', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=200), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub002_dept_id'), 'sub002', ['dept_id'], unique=False)
    op.create_table('sys_dic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dic_code', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('dic_name', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_dic_dic_code'), 'sys_dic', ['dic_code'], unique=True)
    op.create_table('sys_dic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sys_dic_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('value', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('orderby', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=200), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_dept_id'), 'user', ['dept_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('user_role_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_link')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_dept_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('sys_dic_data')
    op.drop_index(op.f('ix_sys_dic_dic_code'), table_name='sys_dic')
    op.drop_table('sys_dic')
    op.drop_index(op.f('ix_sub002_dept_id'), table_name='sub002')
    op.drop_table('sub002')
    op.drop_index(op.f('ix_shop_daily_stat_shop_id'), table_name='shop_daily_stat')
    op.drop_table('shop_daily_stat')
    op.drop_index(op.f('ix_shop_app_code'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_sale_predict_sku'), table_name='sale_predict')
    op.drop_index(op.f('ix_sale_predict_dept_id'), table_name='sale_predict')
    op.drop_table('sale_predict')
    op.drop_table('role_permission_link')
    op.drop_table('role_dept_link')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_code'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_quotes_to_scrape_dept_id'), table_name='quotes_to_scrape')
    op.drop_index(op.f('ix_quotes_to_scrape_author'), table_name='quotes_to_scrape')
    op.drop_table('quotes_to_scrape')
    op.drop_index(op.f('ix_product4_sephora_skuId'), table_name='product4_sephora')
    op.drop_index(op.f('ix_product4_sephora_productId'), table_name='product4_sephora')
    op.drop_index(op.f('ix_product4_sephora_dept_id'), table_name='product4_sephora')
    op.drop_table('product4_sephora')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_menu_permission_code'), table_name='menu')
    op.drop_index(op.f('ix_menu_parent_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_masterdetailrel_parent_menu_id'), table_name='masterdetailrel')
    op.drop_index(op.f('ix_masterdetailrel_master_module_id'), table_name='masterdetailrel')
    op.drop_index(op.f('ix_masterdetailrel_detail_module_id'), table_name='masterdetailrel')
    op.drop_table('masterdetailrel')
    op.drop_index(op.f('ix_main002_dic_code'), table_name='main002')
    op.drop_index(op.f('ix_main002_dept_id'), table_name='main002')
    op.drop_table('main002')
    op.drop_index(op.f('ix_fsa_manage_dept_id'), table_name='fsa_manage')
    op.drop_table('fsa_manage')
    op.drop_index(op.f('ix_fsa_flyer_link_dept_id'), table_name='fsa_flyer_link')
    op.drop_table('fsa_flyer_link')
    op.drop_index(op.f('ix_flyer_main_dept_id'), table_name='flyer_main')
    op.drop_table('flyer_main')
    op.drop_index(op.f('ix_flyer_details_dept_id'), table_name='flyer_details')
    op.drop_table('flyer_details')
    op.drop_index(op.f('ix_flipp_merchant_dept_id'), table_name='flipp_merchant')
    op.drop_table('flipp_merchant')
    op.drop_table('dept')
    op.drop_index(op.f('ix_demo_order01_order_code'), table_name='demo_order01')
    op.drop_index(op.f('ix_demo_order01_dept_id'), table_name='demo_order01')
    op.drop_table('demo_order01')
    op.drop_index(op.f('ix_cruddefinemoduel_parent_menu_id'), table_name='cruddefinemoduel')
    op.drop_index(op.f('ix_cruddefinemoduel_module_name'), table_name='cruddefinemoduel')
    op.drop_index(op.f('ix_cruddefinemoduel_label'), table_name='cruddefinemoduel')
    op.drop_table('cruddefinemoduel')
    op.drop_index(op.f('ix_cruddefinefileds_name'), table_name='cruddefinefileds')
    op.drop_index(op.f('ix_cruddefinefileds_module_id'), table_name='cruddefinefileds')
    op.drop_index(op.f('ix_cruddefinefileds_max_length'), table_name='cruddefinefileds')
    op.drop_index(op.f('ix_cruddefinefileds_default'), table_name='cruddefinefileds')
    op.drop_table('cruddefinefileds')
    op.drop_index(op.f('ix_brand_dept_id'), table_name='brand')
    op.drop_table('brand')
    op.drop_index(op.f('ix_app_name'), table_name='app')
    op.drop_table('app')
    # ### end Alembic commands ###
