"""add module demoUser

Revision ID: bf44afe93c8e
Revises: 9b2b859308f7
Create Date: 2025-07-23 16:36:41.556127

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf44afe93c8e'
down_revision = '9b2b859308f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demouser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('birth_day', sa.DateTime(), nullable=False),
    sa.Column('hobby', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hobby2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demouser_name'), 'demouser', ['name'], unique=False)
    op.drop_index('ix_shop_daily_stat_shop_id', table_name='shop_daily_stat')
    op.drop_table('shop_daily_stat')
    op.drop_index('ix_demoitems_order_id', table_name='demoitems')
    op.drop_table('demoitems')
    op.drop_index('ix_mulcurdmodeluser03_user_code', table_name='mulcurdmodeluser03')
    op.drop_index('ix_mulcurdmodeluser03_user_name', table_name='mulcurdmodeluser03')
    op.drop_table('mulcurdmodeluser03')
    op.drop_index('ix_mulcurdmodelorder03_order_code', table_name='mulcurdmodelorder03')
    op.drop_index('ix_mulcurdmodelorder03_user_id', table_name='mulcurdmodelorder03')
    op.drop_table('mulcurdmodelorder03')
    op.drop_index('ix_app_name', table_name='app')
    op.drop_table('app')
    op.drop_index('ix_demoorder01_order_code', table_name='demoorder01')
    op.drop_table('demoorder01')
    op.drop_index('ix_shop_app_code', table_name='shop')
    op.drop_table('shop')
    op.drop_index('ix_demoorder_order_code', table_name='demoorder')
    op.drop_table('demoorder')
    op.drop_index('ix_curdmodel02_code', table_name='curdmodel02')
    op.drop_index('ix_curdmodel02_name', table_name='curdmodel02')
    op.drop_table('curdmodel02')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curdmodel02',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='curdmodel02_pkey')
    )
    op.create_index('ix_curdmodel02_name', 'curdmodel02', ['name'], unique=True)
    op.create_index('ix_curdmodel02_code', 'curdmodel02', ['code'], unique=True)
    op.create_table('demoorder',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('open_function', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('order_info', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demoorder_pkey')
    )
    op.create_index('ix_demoorder_order_code', 'demoorder', ['order_code'], unique=True)
    op.create_table('shop',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='shop_pkey'),
    sa.UniqueConstraint('code', name='shop_code_key')
    )
    op.create_index('ix_shop_app_code', 'shop', ['app_code'], unique=False)
    op.create_table('demoorder01',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_info', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demoorder01_pkey')
    )
    op.create_index('ix_demoorder01_order_code', 'demoorder01', ['order_code'], unique=True)
    op.create_table('app',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('api_base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('app_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('app_secret', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_pkey'),
    sa.UniqueConstraint('code', name='app_code_key')
    )
    op.create_index('ix_app_name', 'app', ['name'], unique=False)
    op.create_table('mulcurdmodelorder03',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mulcurdmodelorder03_pkey')
    )
    op.create_index('ix_mulcurdmodelorder03_user_id', 'mulcurdmodelorder03', ['user_id'], unique=False)
    op.create_index('ix_mulcurdmodelorder03_order_code', 'mulcurdmodelorder03', ['order_code'], unique=True)
    op.create_table('mulcurdmodeluser03',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_status', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('open_function', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mulcurdmodeluser03_pkey')
    )
    op.create_index('ix_mulcurdmodeluser03_user_name', 'mulcurdmodeluser03', ['user_name'], unique=False)
    op.create_index('ix_mulcurdmodeluser03_user_code', 'mulcurdmodeluser03', ['user_code'], unique=True)
    op.create_table('demoitems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demoitems_pkey')
    )
    op.create_index('ix_demoitems_order_id', 'demoitems', ['order_id'], unique=False)
    op.create_table('shop_daily_stat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pv', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uv', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sales_volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sales_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='shop_daily_stat_pkey')
    )
    op.create_index('ix_shop_daily_stat_shop_id', 'shop_daily_stat', ['shop_id'], unique=False)
    op.drop_index(op.f('ix_demouser_name'), table_name='demouser')
    op.drop_table('demouser')
    # ### end Alembic commands ###
