"""Add module appNew5

Revision ID: c3ddabf7024d
Revises: ac8cd674fd2b
Create Date: 2025-07-15 15:07:57.058831

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c3ddabf7024d'
down_revision = 'ac8cd674fd2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appnew5', 'api_base_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('appnew5', 'app_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('appnew5', 'app_secret',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('appnew5', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appnew5', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('appnew5', 'app_secret',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('appnew5', 'app_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('appnew5', 'api_base_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
