"""Add module

Revision ID: c6134b253383
Revises: ff7ed3fe9076
Create Date: 2025-07-22 10:13:13.977693

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c6134b253383'
down_revision = 'ff7ed3fe9076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cruddefinefileds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('primary_key', sa.Boolean(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('form_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('default', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('insertable', sa.Boolean(), nullable=True),
    sa.Column('updatable', sa.Boolean(), nullable=True),
    sa.Column('listable', sa.Boolean(), nullable=True),
    sa.Column('queryable', sa.Boolean(), nullable=True),
    sa.Column('query_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sortable', sa.Boolean(), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=True),
    sa.Column('unique', sa.Boolean(), nullable=True),
    sa.Column('index', sa.Boolean(), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruddefinefileds_default'), 'cruddefinefileds', ['default'], unique=False)
    op.create_index(op.f('ix_cruddefinefileds_description'), 'cruddefinefileds', ['description'], unique=False)
    op.create_index(op.f('ix_cruddefinefileds_max_length'), 'cruddefinefileds', ['max_length'], unique=False)
    op.create_index(op.f('ix_cruddefinefileds_module_id'), 'cruddefinefileds', ['module_id'], unique=False)
    op.create_index(op.f('ix_cruddefinefileds_name'), 'cruddefinefileds', ['name'], unique=False)
    op.create_table('cruddefinemoduel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruddefinemoduel_label'), 'cruddefinemoduel', ['label'], unique=True)
    op.create_index(op.f('ix_cruddefinemoduel_module_name'), 'cruddefinemoduel', ['module_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cruddefinemoduel_module_name'), table_name='cruddefinemoduel')
    op.drop_index(op.f('ix_cruddefinemoduel_label'), table_name='cruddefinemoduel')
    op.drop_table('cruddefinemoduel')
    op.drop_index(op.f('ix_cruddefinefileds_name'), table_name='cruddefinefileds')
    op.drop_index(op.f('ix_cruddefinefileds_module_id'), table_name='cruddefinefileds')
    op.drop_index(op.f('ix_cruddefinefileds_max_length'), table_name='cruddefinefileds')
    op.drop_index(op.f('ix_cruddefinefileds_description'), table_name='cruddefinefileds')
    op.drop_index(op.f('ix_cruddefinefileds_default'), table_name='cruddefinefileds')
    op.drop_table('cruddefinefileds')
    # ### end Alembic commands ###
