"""update datetime

Revision ID: c7a95007abd6
Revises: 179b5ec525ea
Create Date: 2025-09-04 10:51:48.431883

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7a95007abd6'
down_revision = '179b5ec525ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flyer_details', 'brand',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'cutout_image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'merchant',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flyer_details', 'merchant',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'cutout_image_url',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'brand',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
