"""set predict_quantity default value is -1, to distinguish it from 0

Revision ID: ca121a52726d
Revises: 227a659b5112
Create Date: 2025-08-20 10:38:54.535266

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca121a52726d'
down_revision = '227a659b5112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
