"""set predict_quantity default value is -1, to distinguish it from 0

Revision ID: ca613fa1389e
Revises: 9e7c5bf50a28
Create Date: 2025-08-20 10:30:30.684309

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca613fa1389e'
down_revision = '9e7c5bf50a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
