"""set predict_quantity default value is -1, to distinguish it from 0

Revision ID: ca8f3951336f
Revises: ca613fa1389e
Create Date: 2025-08-20 10:36:46.320457

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca8f3951336f'
down_revision = 'ca613fa1389e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
