"""demoUser add filed23

Revision ID: cd7865fe7427
Revises: 17d8bd6d7e01
Create Date: 2025-07-24 10:31:43.853720

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd7865fe7427'
down_revision = '17d8bd6d7e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
