"""demoUser add filed

Revision ID: cf11a8a1f51a
Revises: bf44afe93c8e
Create Date: 2025-07-24 09:33:23.323754

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cf11a8a1f51a'
down_revision = 'bf44afe93c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demouser', sa.Column('gender2', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demouser', 'gender2')
    # ### end Alembic commands ###
