"""update brand filed

Revision ID: d624268e1dec
Revises: cbdc95c936cf
Create Date: 2025-09-04 16:00:34.019281

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd624268e1dec'
down_revision = 'cbdc95c936cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('en_name', sa.String(length=100), server_default=sa.text("''"), nullable=False))
    op.add_column('brand', sa.Column('original_name', sa.String(length=100), server_default=sa.text("''"), nullable=False))
    op.drop_column('brand', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('brand', 'original_name')
    op.drop_column('brand', 'en_name')
    # ### end Alembic commands ###
