"""add content length to 5000

Revision ID: d71166f92651
Revises: 430de3d11030
Create Date: 2025-08-26 15:32:25.726550

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd71166f92651'
down_revision = '430de3d11030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes_to_scrape', 'content',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=5000),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes_to_scrape', 'content',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
