"""add flipp

Revision ID: dd5e8663daaf
Revises: 63d86518eda7
Create Date: 2025-09-02 11:42:56.840682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd5e8663daaf'
down_revision = '63d86518eda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flipp_merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('merchant_logo', sa.String(length=250), server_default=sa.text("''"), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flipp_merchant_dept_id'), 'flipp_merchant', ['dept_id'], unique=False)
    op.create_table('flyer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), server_default=sa.text("''"), nullable=False),
    sa.Column('brand', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('valid_from', sa.String(), nullable=False),
    sa.Column('valid_to', sa.String(), nullable=False),
    sa.Column('available_to', sa.String(), nullable=False),
    sa.Column('cutout_image_url', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('price', sa.String(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('flyer_id', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flyer_details_dept_id'), 'flyer_details', ['dept_id'], unique=False)
    op.create_table('flyer_main',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('valid_from', sa.String(), nullable=False),
    sa.Column('valid_to', sa.String(), nullable=False),
    sa.Column('categories', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('fly_id', sa.Integer(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flyer_main_dept_id'), 'flyer_main', ['dept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flyer_main_dept_id'), table_name='flyer_main')
    op.drop_table('flyer_main')
    op.drop_index(op.f('ix_flyer_details_dept_id'), table_name='flyer_details')
    op.drop_table('flyer_details')
    op.drop_index(op.f('ix_flipp_merchant_dept_id'), table_name='flipp_merchant')
    op.drop_table('flipp_merchant')
    # ### end Alembic commands ###
