"""update order model

Revision ID: e168cabb5097
Revises: 2f29b7e445b2
Create Date: 2025-07-17 15:38:26.014315

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e168cabb5097'
down_revision = '2f29b7e445b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mulcurdmodelorder_user_id', table_name='mulcurdmodelorder')
    op.create_index(op.f('ix_mulcurdmodelorder_user_id'), 'mulcurdmodelorder', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mulcurdmodelorder_user_id'), table_name='mulcurdmodelorder')
    op.create_index('ix_mulcurdmodelorder_user_id', 'mulcurdmodelorder', ['user_id'], unique=True)
    # ### end Alembic commands ###
