"""update table name

Revision ID: ece18cd6f3b5
Revises: 9bd4ef5e5e8f
Create Date: 2025-07-24 14:30:30.915495

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ece18cd6f3b5'
down_revision = '9bd4ef5e5e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dic_code', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('dic_name', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_dic_dic_code'), 'sys_dic', ['dic_code'], unique=True)
    op.create_table('sys_dic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sys_dic_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('value', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('orderby', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=200), server_default=sa.text("''"), nullable=True),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_sysdic_dic_code', table_name='sysdic')
    op.drop_table('sysdic')
    op.drop_table('sysdicdata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysdicdata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sys_dic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orderby', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sysdicdata_pkey')
    )
    op.create_table('sysdic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dic_code', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('dic_name', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sysdic_pkey')
    )
    op.create_index('ix_sysdic_dic_code', 'sysdic', ['dic_code'], unique=True)
    op.drop_table('sys_dic_data')
    op.drop_index(op.f('ix_sys_dic_dic_code'), table_name='sys_dic')
    op.drop_table('sys_dic')
    # ### end Alembic commands ###
