"""update filed length

Revision ID: f6f0e71e9352
Revises: 8b1f2c5f1c73
Create Date: 2025-09-10 12:00:25.024462

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f6f0e71e9352'
down_revision = '8b1f2c5f1c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flyer_details', 'name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'brand',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'cutout_image_url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'merchant',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'cn_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'hk_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flyer_details', 'hk_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'cn_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'merchant',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'cutout_image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'brand',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('flyer_details', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
