"""add crud module 001

Revision ID: f8ac07cb7c30
Revises: 620cda713296
Create Date: 2025-07-21 15:40:11.029730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f8ac07cb7c30'
down_revision = '620cda713296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crud_define_filed', sa.Column('query_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('crud_define_filed', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('crud_define_filed', 'options',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('crud_define_filed', 'max_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crud_define_filed', 'default',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crud_define_filed', 'default',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('crud_define_filed', 'max_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crud_define_filed', 'options',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('crud_define_filed', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('crud_define_filed', 'query_type')
    # ### end Alembic commands ###
