"""add module masterDetailRel

Revision ID: fc89b2a8ed67
Revises: 7a2f5da1363c
Create Date: 2025-07-22 16:44:17.344970

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc89b2a8ed67'
down_revision = '7a2f5da1363c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masterdetailrel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_module_id', sa.Integer(), nullable=False),
    sa.Column('detail_module_id', sa.Integer(), nullable=False),
    sa.Column('rel_filed_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('updater', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masterdetailrel_detail_module_id'), 'masterdetailrel', ['detail_module_id'], unique=False)
    op.create_index(op.f('ix_masterdetailrel_master_module_id'), 'masterdetailrel', ['master_module_id'], unique=False)
    op.drop_index('ix_crud_define_filed_default', table_name='crud_define_filed')
    op.drop_index('ix_crud_define_filed_description', table_name='crud_define_filed')
    op.drop_index('ix_crud_define_filed_max_length', table_name='crud_define_filed')
    op.drop_index('ix_crud_define_filed_module_id', table_name='crud_define_filed')
    op.drop_index('ix_crud_define_filed_name', table_name='crud_define_filed')
    op.drop_table('crud_define_filed')
    op.drop_index('ix_crud_define_moduel_label', table_name='crud_define_moduel')
    op.drop_index('ix_crud_define_moduel_module_name', table_name='crud_define_moduel')
    op.drop_table('crud_define_moduel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crud_define_moduel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='crud_define_moduel_pkey')
    )
    op.create_index('ix_crud_define_moduel_module_name', 'crud_define_moduel', ['module_name'], unique=True)
    op.create_index('ix_crud_define_moduel_label', 'crud_define_moduel', ['label'], unique=True)
    op.create_table('crud_define_filed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('form_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('options', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('max_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('default', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('insertable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updatable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queryable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sortable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nullable', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unique', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updater', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('query_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='crud_define_filed_pkey')
    )
    op.create_index('ix_crud_define_filed_name', 'crud_define_filed', ['name'], unique=False)
    op.create_index('ix_crud_define_filed_module_id', 'crud_define_filed', ['module_id'], unique=False)
    op.create_index('ix_crud_define_filed_max_length', 'crud_define_filed', ['max_length'], unique=False)
    op.create_index('ix_crud_define_filed_description', 'crud_define_filed', ['description'], unique=False)
    op.create_index('ix_crud_define_filed_default', 'crud_define_filed', ['default'], unique=False)
    op.drop_index(op.f('ix_masterdetailrel_master_module_id'), table_name='masterdetailrel')
    op.drop_index(op.f('ix_masterdetailrel_detail_module_id'), table_name='masterdetailrel')
    op.drop_table('masterdetailrel')
    # ### end Alembic commands ###
