"""add filed sku

Revision ID: fdba3ddcf1ec
Revises: 95ea25fdb4a2
Create Date: 2025-08-18 12:28:34.960921

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fdba3ddcf1ec'
down_revision = '95ea25fdb4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_predict', sa.Column('sku', sa.String(length=20), server_default=sa.text("''"), nullable=False))
    op.create_index(op.f('ix_sale_predict_sku'), 'sale_predict', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_predict_sku'), table_name='sale_predict')
    op.drop_column('sale_predict', 'sku')
    # ### end Alembic commands ###
