"""modify options

Revision ID: ff7ed3fe9076
Revises: f8ac07cb7c30
Create Date: 2025-07-21 16:29:43.374429

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ff7ed3fe9076'
down_revision = 'f8ac07cb7c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crud_define_filed', 'options',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1024),
               existing_nullable=True)
    op.drop_index('ix_crud_define_filed_options', table_name='crud_define_filed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_crud_define_filed_options', 'crud_define_filed', ['options'], unique=False)
    op.alter_column('crud_define_filed', 'options',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
