# This file is auto-generated by the codegen tool.
# just a placeholder for the actual code generation logic
from app.api.routes import (
    demoUser
)
...
api_router.include_router(demoUser.router, prefix="/demoUser", tags=["DemoUser"])
...