# This file is auto-generated by the codegen tool.
# just a placeholder for the actual code generation logic
from app.api.routes import (
    curdModel02
)
...
api_router.include_router(curdModel02.router, prefix="/curdModel02", tags=["CurdModel02"])
...