# This file is auto-generated by the codegen tool.
# just a placeholder for the actual code generation logic
from app.api.routes import (
    menu
)
...
api_router.include_router(menu.router, prefix="/menu", tags=["Menu"])
...